BEGIN;

DROP TABLE IF EXISTS sleep_record CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS emotion_log CASCADE;
DROP TABLE IF EXISTS user_address CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP TYPE IF EXISTS day_period;
DROP TYPE IF EXISTS emotion_type;

DROP EXTENSION IF EXISTS "uuid-ossp";

COMMIT;